<a href="https://colab.research.google.com/github/milosavljeviciva/domaci/blob/main/IvaMilosavljevic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
data = pd.read_csv("./sample_data/mnist_train_small.csv")

from sklearn.model_selection import train_test_split
data = data.rename(columns={"6": "label"})
data.head()
print(data.shape)

train, test = train_test_split(data, test_size=0.2)

(19999, 785)


In [ ]:
train = np.array(train)
test = np.array(test)

train = train.T

y_train = train[0]
X_train = train[1:]
print(X_train.shape)
m = X_train.shape[1]
X_train = X_train / 255
print(y_train)

(784, 15999)
[8 8 7 ... 8 4 4]


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(784, 100),
            nn.ReLU(),
            nn.Linear(100, 10),
            nn.Softmax()
        )

    def forward(self, x):
        return self.net(x)

    def predict(self, x):
        out = self.forward(x)
        out = torch.argmax(out, dim=1)
        return out

In [ ]:
import torch.nn.functional as F
def fit(X, y, model, epoch, loss_fn, opt):
    ohy = F.one_hot(y.to(torch.int64), 10).float()
    for i in range(epoch):
        loss = loss_fn(model.forward(X), ohy)
        loss.backward()
        opt.step()
        opt.zero_grad()
        out = model.predict(X)
        print(out)
        print(y)
        acc = accuracy(out, y)
        print(i, "Accuracy: ", acc)

def accuracy(pred, actual):
    s = torch.sum(pred == actual)
    return s.item() / len(actual)

In [ ]:
import torch.optim as optim
import torch.nn.functional as F
import torch
model = Model()
epochs = 80
lr = 0.01
opt = optim.Adam(model.parameters(), lr=lr)
loss = F.cross_entropy

X = torch.from_numpy(X_train.T).float()
y = torch.from_numpy(y_train).long()
fit(X, y, model, epochs, loss, opt)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([9, 7, 7,  ..., 9, 9, 9])
tensor([8, 8, 7,  ..., 8, 4, 4])
0 Accuracy:  0.46052878304894057
tensor([2, 3, 7,  ..., 0, 4, 7])
tensor([8, 8, 7,  ..., 8, 4, 4])
1 Accuracy:  0.4499656228514282
tensor([2, 3, 7,  ..., 2, 4, 7])
tensor([8, 8, 7,  ..., 8, 4, 4])
2 Accuracy:  0.518032377023564
tensor([4, 3, 7,  ..., 3, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
3 Accuracy:  0.6368523032689543
tensor([4, 3, 7,  ..., 3, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
4 Accuracy:  0.6701043815238452
tensor([4, 3, 7,  ..., 9, 4, 9])
tensor([8, 8, 7,  ..., 8, 4, 4])
5 Accuracy:  0.6848553034564661
tensor([4, 3, 7,  ..., 9, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
6 Accuracy:  0.7184824051503219
tensor([4, 3, 7,  ..., 8, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
7 Accuracy:  0.7528595537221077
tensor([4, 3, 7,  ..., 8, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
8 Accuracy:  0.7805487842990186
tensor([4, 3, 7,  ..., 8, 4, 4])
tensor([8, 8, 7,  ..., 8, 4, 4])
9 Accuracy:  0.7804237764860303
tensor([4, 3, 7,  ..