<a href="https://colab.research.google.com/github/milosavljeviciva/domaci/blob/main/mnist_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv("./sample_data/mnist_train_small.csv")

In [18]:
from sklearn.model_selection import train_test_split
data = data.rename(columns = {"6": "label"})
data.head()
print(data.shape)

train, test = train_test_split(data, test_size = 0.2)


(19999, 785)


In [21]:
train.hist(columns)
test.hist(columns)

AttributeError: 'numpy.ndarray' object has no attribute 'hist'

In [19]:
train = np.array(train)
test = np.array(test)
train_X = train[:, 1:].T
train_y = train[:,0]
print(train_X)
print(train_y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0 9 1 ... 0 9 1]


In [20]:
def ReLu(x):
  return max(0, x)

def deriv_ReLu(X):
  return X > 0

def softmax(X):
  return np.exp(X) / np.sum(exp(X))

def init_params():
  W1 = np.random.randn(10, 784)
  b1 = np.random.randn(10, 1)
  W2 = np.random.randn(20, 20)
  b2 = np.random.randn(20, 1)
  return W1, b1, W2, b2

def one_hot(X):
  r = np.zeros(10)
  r[X] = 1
  return r

def forward(W1, b1, W2, b2, X):
  z1 = W1.dot(X) + b1
  a1 = ReLu(z1)
  z2 = W2.dot(a1) + b2
  a2 = softmax(z2)
  return z1, a1, z2, a2

def backward(z1, a1, z2, a2, W2, X, y):
  m = y.size
  oh_y = one_hot(y)
  dz2 = a2 - oh_y
  dw2 = 1 / m * dz2.dot(a1.T)
  db2 = 1 / m * np.sum(dz2, 2)
  dz1 = W2.T.dot(dz2) * deriv_ReLu(z1)
  dw1 = 1 / m * dz1.dot(X.T)
  db1 = 1 / m * np.sum(dz1, 2)
  return dw1, db1, dw2, db2

def update_params(W1, b1, W2, b2, dw1, db1, dw2, db2, lr):
  W1 -= lr * dw1
  W2 -= lr * dw2
  b1 -= lr * db1
  b2 -= lr * db2
  return W1, b1, W2, b2

def gradiend_descent(X, Y, iterations, lr):
  W1, b1, W2, b2 = init_params()
  for i in range(iterations):
    Z1, A1, Z2, A2 = forward(W1, b1, W2, b2, X)
    dW1, db1, dW2, db2 = backward(Z1, A1, Z2, A2, W2, X, Y)
    W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, lr)
    if i % 50 == 0:
      print("Iterations: ", i)
      print("Accuracy: ", get_accuracy(get_prediction(A2), Y))

In [ ]:
W1, b1, W2, b2 = gradient_descent(train_X, train_y, 100, 0)